import { Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native'
import * as Clipboard from 'expo-clipboard'
import { ChevronLeft, ChevronRight, Copy, Heart, Pause, Play, Share2 } from 'lucide-react-native'
import { useAppStore } from '@/store/useAppStore'
import { formatMs, formatTimestamp, formatVerseRef } from '@/utils/format'

export function Display({ view }: { view: 'home' | 'favorites' | 'history' }) {
  const verse = useAppStore(s => s.currentVerse); const quote = useAppStore(s => s.currentQuote); const settings = useAppStore(s => s.settings); const history = useAppStore(s => s.history); const favoriteVerses = useAppStore(s => s.favoriteVerses); const favoriteQuotes = useAppStore(s => s.favoriteQuotes); const bibleRemainingMs = useAppStore(s => s.bibleRemainingMs); const quoteRemainingMs = useAppStore(s => s.quoteRemainingMs); const nextVerse = useAppStore(s => s.nextVerse); const prevVerse = useAppStore(s => s.prevVerse); const nextQuote = useAppStore(s => s.nextQuote); const prevQuote = useAppStore(s => s.prevQuote); const toggleVerse = useAppStore(s => s.toggleFavoriteVerse); const toggleQuote = useAppStore(s => s.toggleFavoriteQuote); const pause = useAppStore(s => s.pause); const resume = useAppStore(s => s.resume)
  if (!verse || !quote) return null
  if (view === 'favorites') return <ScrollView contentContainerStyle={styles.page}><Text style={styles.sectionTitle}>Saved for later</Text>{favoriteVerses.length + favoriteQuotes.length === 0 ? <Empty label="Heart a verse or quote to keep it here." /> : <>{favoriteVerses.map(v => <Saved key={v.id} text={v.text} source={formatVerseRef(v)} onRemove={() => toggleVerse(v.id)} />)}{favoriteQuotes.map(q => <Saved key={q.id} text={q.text} source={q.author} onRemove={() => toggleQuote(q.id)} />)}</>}</ScrollView>
  if (view === 'history') return <ScrollView contentContainerStyle={styles.page}><Text style={styles.sectionTitle}>Recently displayed</Text>{history.length === 0 ? <Empty label="Your displayed verses and quotes will appear here." /> : history.slice(0, 50).map(item => <View style={styles.history} key={item.id}><Text style={styles.historyTime}>{formatTimestamp(item.displayedAt)}</Text><Text style={styles.historyCopy}>Verse and motivation were refreshed</Text></View>)}</ScrollView>
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.themePill}><Text style={styles.themeText}>TODAY'S FOCUS · {verse.category.toUpperCase()}</Text></View><View style={styles.hero}><Text style={styles.label}>SCRIPTURE</Text><Text style={styles.verse}>"{verse.text}"</Text><Text style={styles.reference}>- {formatVerseRef(verse)} <Text style={styles.translation}>{verse.translation}</Text></Text><Controls onPrev={prevVerse} onNext={nextVerse} favorite={verse.favorite} onFavorite={() => toggleVerse(verse.id)} text={`"${verse.text}" - ${formatVerseRef(verse)} (${verse.translation})`} /></View><View style={styles.quoteCard}><View style={styles.quoteHeader}><Text style={styles.label}>MOTIVATION</Text><Text style={styles.timer}>NEXT IN {formatMs(quoteRemainingMs)}</Text></View><Text style={styles.quote}>"{quote.text}"</Text><Text style={styles.author}>- {quote.author}</Text><Controls onPrev={prevQuote} onNext={nextQuote} favorite={quote.favorite} onFavorite={() => toggleQuote(quote.id)} text={`"${quote.text}" - ${quote.author}`} small /></View><View style={styles.status}><View><Text style={styles.statusLabel}>Scripture refresh</Text><Text style={styles.statusValue}>{settings.isPaused ? 'Paused' : `in ${formatMs(bibleRemainingMs)}`}</Text></View><Pressable onPress={settings.isPaused ? resume : pause} style={styles.pause}>{settings.isPaused ? <Play size={16} color="#FFF" fill="#FFF" /> : <Pause size={16} color="#FFF" fill="#FFF" />}<Text style={styles.pauseText}>{settings.isPaused ? 'Resume' : 'Pause'}</Text></Pressable></View></ScrollView>
}
function Controls({ onPrev, onNext, favorite, onFavorite, text, small }: any) { const copy = () => Clipboard.setStringAsync(text); const share = () => Share.share({ message: text }); return <View style={[styles.controls, small && styles.controlsSmall]}><Pressable accessibilityLabel="Previous" onPress={onPrev} style={styles.icon}><ChevronLeft size={19} color="#66756D" /></Pressable><Pressable accessibilityLabel="Favorite" onPress={onFavorite} style={styles.icon}><Heart size={18} color={favorite ? '#C46A6A' : '#66756D'} fill={favorite ? '#C46A6A' : 'transparent'} /></Pressable><Pressable accessibilityLabel="Copy" onPress={copy} style={styles.icon}><Copy size={16} color="#66756D" /></Pressable><Pressable accessibilityLabel="Share" onPress={share} style={styles.icon}><Share2 size={16} color="#66756D" /></Pressable><Pressable accessibilityLabel="Next" onPress={onNext} style={styles.icon}><ChevronRight size={19} color="#66756D" /></Pressable></View> }
function Saved({ text, source, onRemove }: { text: string; source: string; onRemove: () => void }) { return <View style={styles.saved}><Text style={styles.savedText}>“{text}”</Text><View style={styles.savedFooter}><Text style={styles.savedSource}>— {source}</Text><Pressable onPress={onRemove}><Heart size={18} color="#C46A6A" fill="#C46A6A" /></Pressable></View></View> }; function Empty({ label }: { label: string }) { return <View style={styles.empty}><Heart size={30} color="#B7C3B9" /><Text style={styles.emptyText}>{label}</Text></View> }
const styles = StyleSheet.create({ page: { padding: 26, gap: 18, maxWidth: 900, width: '100%', alignSelf: 'center' }, themePill: { alignSelf: 'flex-start', backgroundColor: '#EBF0E8', borderRadius: 4, paddingHorizontal: 9, paddingVertical: 5 }, themeText: { color: '#52705D', fontWeight: '800', fontSize: 10, letterSpacing: 1 }, hero: { backgroundColor: '#25332D', borderRadius: 8, padding: 28, minHeight: 265, justifyContent: 'center' }, label: { color: '#C9A857', fontWeight: '800', letterSpacing: 1.4, fontSize: 10 }, verse: { color: '#FAF8F0', fontSize: 27, lineHeight: 38, fontFamily: 'serif', marginTop: 13 }, reference: { color: '#D7E0D8', marginTop: 16, fontSize: 14, fontWeight: '700' }, translation: { color: '#C9A857', fontSize: 11 }, controls: { flexDirection: 'row', gap: 10, marginTop: 23 }, controlsSmall: { marginTop: 16 }, icon: { width: 34, height: 30, borderRadius: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF1EC' }, quoteCard: { borderWidth: 1, borderColor: '#E0E4DC', borderRadius: 8, padding: 21, backgroundColor: '#FFF' }, quoteHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, timer: { color: '#89948D', fontSize: 10, fontWeight: '700', letterSpacing: .6 }, quote: { color: '#2C3933', fontSize: 18, lineHeight: 27, marginTop: 12 }, author: { color: '#6B776F', fontSize: 13, marginTop: 9 }, status: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10 }, statusLabel: { color: '#68756D', fontSize: 12 }, statusValue: { color: '#27362F', fontSize: 15, fontWeight: '700', marginTop: 3 }, pause: { flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#355A49', paddingHorizontal: 14, height: 38, borderRadius: 6 }, pauseText: { color: '#FFF', fontWeight: '700', fontSize: 13 }, sectionTitle: { color: '#24342C', fontSize: 24, fontWeight: '700', marginBottom: 4 }, saved: { backgroundColor: '#FFF', borderRadius: 8, borderWidth: 1, borderColor: '#E0E4DC', padding: 17 }, savedText: { color: '#2B3B32', fontSize: 15, lineHeight: 22 }, savedFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 }, savedSource: { color: '#69776E', fontSize: 12, fontWeight: '700' }, empty: { alignItems: 'center', paddingTop: 80, gap: 13 }, emptyText: { color: '#6D7A72', textAlign: 'center' }, history: { backgroundColor: '#FFF', borderRadius: 7, padding: 16, borderWidth: 1, borderColor: '#E0E4DC' }, historyTime: { color: '#52705D', fontSize: 12, fontWeight: '700' }, historyCopy: { marginTop: 5, color: '#69776E' } })
